<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Regenerates the committed intrinsic-dimension manifest for static assets.
 *
 * Every `<img>` on the site needs explicit width/height so the browser can
 * reserve space before the image loads (this is what removes layout shift).
 * Static template assets live under public/assets and are not in the media
 * table, so their real dimensions are recorded here once and committed.
 *
 * Run this only when static assets are added or replaced. Reading dimensions
 * at request time would mean filesystem I/O on every page render, which is
 * exactly what the manifest avoids.
 */
class BuildImageManifest extends Command
{
    protected $signature = 'images:manifest {--check : Fail if the manifest is out of date}';

    protected $description = 'Rebuild resources/image-dimensions.php from the real static assets';

    public function handle(): int
    {
        $directory = public_path('assets/images');
        $target = resource_path('image-dimensions.php');

        if (! is_dir($directory)) {
            $this->error("Missing directory: {$directory}");

            return self::FAILURE;
        }

        $entries = [];

        foreach (scandir($directory) ?: [] as $file) {
            if (in_array($file, ['.', '..'], true)) {
                continue;
            }

            $path = $directory.DIRECTORY_SEPARATOR.$file;
            $size = @getimagesize($path);

            if ($size === false) {
                continue;
            }

            // SVGs are deliberately excluded. An SVG already declares its own
            // width/height/viewBox, so the browser knows its ratio without any
            // attribute, and adding width/height here would risk overriding the
            // ratio the template's CSS depends on (the service icons are
            // rendered at width="40" regardless of their intrinsic size).
            if (strtolower(pathinfo($file, PATHINFO_EXTENSION)) === 'svg') {
                continue;
            }

            // Keyed by the public-relative path the templates actually use.
            $entries['assets/images/'.$file] = [$size[0], $size[1]];
        }

        ksort($entries);

        $php = "<?php\n\n"
            ."/**\n"
            ." * Intrinsic dimensions of the static template assets under public/assets/images.\n"
            ." *\n"
            ." * Generated by `php artisan images:manifest` from the real files; committed so\n"
            ." * rendering never touches the filesystem. Used to emit width/height on every\n"
            ." * <img>, which is what lets the browser reserve space and keeps CLS at zero.\n"
            ." *\n"
            ." * @var array<string, array{0: int, 1: int}>\n"
            ." */\n\n"
            .'return '.$this->export($entries).";\n";

        if ($this->option('check')) {
            $current = is_file($target) ? file_get_contents($target) : '';

            if ($current !== $php) {
                $this->error('Image dimension manifest is out of date. Run: php artisan images:manifest');

                return self::FAILURE;
            }

            $this->info('Image dimension manifest is up to date ('.count($entries).' entries).');

            return self::SUCCESS;
        }

        file_put_contents($target, $php);

        $this->info('Wrote '.count($entries).' entries to '.$target);

        return self::SUCCESS;
    }

    /**
     * Export the map in the same shape PHP's var_export would, but with short
     * array syntax so the committed file matches project style.
     *
     * @param  array<string, array{0: int, 1: int}>  $entries
     */
    private function export(array $entries): string
    {
        $lines = ['['];

        foreach ($entries as $path => $dimensions) {
            $lines[] = sprintf("    '%s' => [%d, %d],", $path, $dimensions[0], $dimensions[1]);
        }

        $lines[] = ']';

        return implode("\n", $lines);
    }
}
