<?php

/**
 * Intrinsic dimensions of the static template assets under public/assets/images.
 *
 * Generated by `php artisan images:manifest` from the real files; committed so
 * rendering never touches the filesystem. Used to emit width/height on every
 * <img>, which is what lets the browser reserve space and keeps CLS at zero.
 *
 * @var array<string, array{0: int, 1: int}>
 */

return [
    'assets/images/avatar-1.png' => [100, 100],
    'assets/images/avatar-2.png' => [100, 100],
    'assets/images/avatar-3.png' => [100, 100],
    'assets/images/avatar-4.png' => [100, 100],
    'assets/images/blog-1.jpg' => [601, 401],
    'assets/images/blog-2.jpg' => [601, 401],
    'assets/images/blog-3.jpg' => [601, 401],
    'assets/images/blog-4.jpg' => [601, 401],
    'assets/images/blog-5.jpg' => [600, 391],
    'assets/images/blog-6.jpg' => [600, 394],
    'assets/images/logo-1-color.png' => [209, 131],
    'assets/images/logo-2-color.png' => [209, 131],
    'assets/images/logo-3-color.png' => [209, 131],
    'assets/images/logo-4-color.png' => [209, 131],
    'assets/images/logo-5-color.png' => [209, 131],
    'assets/images/logo-6-color.png' => [209, 131],
    'assets/images/logo.ico' => [256, 256],
    'assets/images/my-avatar.png' => [200, 196],
    'assets/images/project-1.jpg' => [600, 451],
    'assets/images/project-2.png' => [600, 450],
    'assets/images/project-3.jpg' => [600, 451],
    'assets/images/project-4.png' => [600, 450],
    'assets/images/project-5.png' => [600, 450],
    'assets/images/project-6.png' => [600, 450],
    'assets/images/project-7.png' => [600, 450],
    'assets/images/project-8.jpg' => [600, 451],
    'assets/images/project-9.png' => [600, 450],
];
